/**
 * Selectores de columnas SQL usados por las paginas del proyecto.
 *
 * Extraidos literalmente de los *_SELECT locales existentes en src/pages/ y
 * src/hooks/. Donde dos paginas usan el "mismo" nombre pero listas de
 * columnas distintas, se conservan como variantes nombradas por pagina en
 * lugar de fusionarlas: son proyecciones distintas, no duplicados exactos.
 *
 * Este archivo es un catalogo de referencia. Las paginas listadas siguen
 * usando sus propias constantes locales; migrar cada pagina a importar desde
 * aqui requiere revisión y prueba caso por caso (ver docs/control/06_BITACORA_CAMBIOS.md).
 */

export const QUERY_COLUMNS = {
  casos: {
    // CasoDetallePage.tsx
    detalle: [
      'id_caso',
      'paciente_id',
      'consulta_id',
      'evaluacion_id',
      'fecha_apertura',
      'hora_apertura',
      'nombre_caso',
      'motivo_apertura',
      'descripcion_general',
      'objetivo_trabajo',
      'tipo_caso',
      'prioridad',
      'estado_caso',
      'requiere_seguimiento',
      'notas_seguimiento',
      'fecha_cierre',
      'resultado_cierre',
      'notas_internas',
      'created_at',
      'updated_at',
    ].join(', '),
    // CasosPage.tsx (proyeccion mas acotada, sin hora_apertura/fecha_cierre/resultado_cierre/notas_internas/updated_at)
    listado: [
      'id_caso',
      'paciente_id',
      'consulta_id',
      'evaluacion_id',
      'fecha_apertura',
      'nombre_caso',
      'motivo_apertura',
      'descripcion_general',
      'objetivo_trabajo',
      'tipo_caso',
      'prioridad',
      'estado_caso',
      'requiere_seguimiento',
      'notas_seguimiento',
      'created_at',
    ].join(', '),
  },

  consultas: {
    // CasoDetallePage.tsx (sin created_at)
    detalle: [
      'id_consulta',
      'paciente_id',
      'fecha_consulta',
      'hora_inicio',
      'hora_termino',
      'tipo_consulta',
      'modalidad',
      'estado_consulta',
      'motivo_consulta',
      'resumen_consulta',
      'observaciones_internas',
    ].join(', '),
    // ConsultasPage.tsx (con created_at)
    listado: [
      'id_consulta',
      'paciente_id',
      'fecha_consulta',
      'hora_inicio',
      'hora_termino',
      'tipo_consulta',
      'modalidad',
      'estado_consulta',
      'motivo_consulta',
      'resumen_consulta',
      'observaciones_internas',
      'created_at',
    ].join(', '),
  },

  evaluaciones: {
    // CasoDetallePage.tsx (sin created_at)
    detalle: [
      'id_evaluacion',
      'paciente_id',
      'consulta_id',
      'fecha_evaluacion',
      'hora_evaluacion',
      'relato_antecedentes',
      'sintomas_reportados',
      'hechos_clave',
      'personas_mencionadas',
      'decision_revision',
      'fundamento_decision',
      'notas_internas',
      'estado_evaluacion',
    ].join(', '),
    // EvaluacionesPage.tsx (con created_at)
    listado: [
      'id_evaluacion',
      'paciente_id',
      'consulta_id',
      'fecha_evaluacion',
      'hora_evaluacion',
      'relato_antecedentes',
      'sintomas_reportados',
      'hechos_clave',
      'personas_mencionadas',
      'decision_revision',
      'fundamento_decision',
      'notas_internas',
      'estado_evaluacion',
      'created_at',
    ].join(', '),
  },

  trabajos: {
    // casos/TrabajosCasoPanel.tsx
    listado: [
      'id_trabajo',
      'paciente_id',
      'caso_id',
      'revision_inicial_id',
      'revision_cierre_id',
      'fecha_inicio',
      'fecha_estimada_cierre',
      'fecha_cierre',
      'numero_trabajo',
      'nombre_trabajo',
      'tipo_trabajo',
      'ambito_trabajo',
      'modalidad_ejecucion',
      'fase_actual',
      'alcance_trabajo',
      'metodo_principal',
      'objetivo_trabajo',
      'prioridad_trabajo',
      'porcentaje_avance_general',
      'requiere_seguimiento',
      'proxima_accion',
      'resultado_general',
      'estado_trabajo',
      'observaciones',
      'created_at',
    ].join(', '),
  },

  cobros: {
    // casos/PagosCasoPanel.tsx
    listado: [
      'id_cobro',
      'paciente_id',
      'caso_id',
      'revision_id',
      'trabajo_id',
      'fecha_cobro',
      'fecha_vencimiento',
      'concepto_cobro',
      'tipo_cobro',
      'monto_cobro',
      'monto_descuento',
      'monto_total',
      'moneda',
      'estado_cobro',
      'monto_pagado',
      'saldo_pendiente',
      'estado_calculado',
    ].join(', '),
  },

  pagos: {
    // casos/PagosCasoPanel.tsx
    listado: [
      'id_pago',
      'cobro_id',
      'paciente_id',
      'fecha_pago',
      'monto_pago',
      'moneda',
      'metodo_pago',
      'estado_pago',
      'referencia_pago',
      'observaciones',
      'created_at',
    ].join(', '),
  },

  unidadesCobrables: {
    // FinanzasPage.tsx (incluye paciente_id y monto_descuento)
    finanzas: [
      'id_cobro',
      'id_pago',
      'paciente_id',
      'codigo_paciente',
      'alias_administrativo_paciente',
      'tipo_unidad_cobrable',
      'referencia_unidad_administrativa',
      'concepto_cobro_administrativo',
      'fecha_cobro',
      'fecha_vencimiento',
      'tipo_cobro',
      'monto_cobro',
      'monto_descuento',
      'monto_total',
      'moneda',
      'estado_cobro',
      'monto_pagado',
      'saldo_pendiente',
      'estado_pago',
      'fecha_ultimo_pago',
      'metodo_ultimo_pago',
      'referencia_pago',
    ].join(', '),
    // ReportesPage.tsx (sin paciente_id ni monto_descuento)
    reportes: [
      'id_cobro',
      'id_pago',
      'codigo_paciente',
      'alias_administrativo_paciente',
      'tipo_unidad_cobrable',
      'referencia_unidad_administrativa',
      'concepto_cobro_administrativo',
      'fecha_cobro',
      'fecha_vencimiento',
      'tipo_cobro',
      'monto_cobro',
      'monto_total',
      'monto_pagado',
      'saldo_pendiente',
      'moneda',
      'estado_cobro',
      'estado_pago',
      'fecha_ultimo_pago',
      'metodo_ultimo_pago',
      'referencia_pago',
    ].join(', '),
  },

  elementosCaso: {
    // casos/ElementosCasoPanel.tsx
    listado: [
      'id_elemento_caso',
      'paciente_id',
      'caso_id',
      'tipo_elemento',
      'nombre_elemento',
      'vinculo_con_paciente',
      'rol_en_caso',
      'prioridad_elemento',
      'orden_elemento',
      'fecha_nacimiento',
      'descripcion_referencia',
      'antecedentes_relevantes',
      'motivo_inclusion',
      'fuente_informacion',
      'nivel_confirmacion',
      'estado_elemento',
      'notas_internas',
      'created_at',
    ].join(', '),
  },

  fotosElementosCaso: {
    // casos/ElementosCasoPanel.tsx
    listado: [
      'id_foto_elemento_caso',
      'paciente_id',
      'caso_id',
      'elemento_caso_id',
      'bucket_id',
      'storage_path',
      'nombre_archivo',
      'mime_type',
      'tamano_bytes',
      'descripcion',
      'tipo_foto',
      'es_principal',
      'estado_foto',
      'created_at',
    ].join(', '),
  },

  revisiones: {
    // casos/RevisionesCasoPanel.tsx
    listado: [
      'id_revision',
      'paciente_id',
      'caso_id',
      'consulta_id',
      'evaluacion_id',
      'fecha_revision',
      'hora_inicio',
      'hora_termino',
      'numero_revision',
      'tipo_revision',
      'modalidad',
      'metodo_revision',
      'alcance_revision',
      'objetivo_revision',
      'resumen_general',
      'resultado_general',
      'requiere_seguimiento',
      'proxima_accion',
      'estado_revision',
      'notas_internas',
      'created_at',
    ].join(', '),
  },

  revisionAspectos: {
    // casos/DetalleRevisionesPanel.tsx
    listado: [
      'id_revision_aspecto',
      'paciente_id',
      'caso_id',
      'revision_id',
      'revision_elemento_id',
      'elemento_caso_id',
      'orden_aspecto',
      'area_revision',
      'aspecto_revisado',
      'metodo_revision',
      'tipo_medicion',
      'metrica_revision',
      'valor_porcentaje',
      'presencia_detectada',
      'tipo_detectado',
      'estado_revision_aspecto',
      'resultado_aspecto',
      'requiere_seguimiento',
      'pendiente_revision',
      'motivo_pendiente',
      'informacion_canalizada',
      'observaciones',
      'notas_internas',
      'created_at',
    ].join(', '),
  },

  revisionElementos: {
    // casos/DetalleRevisionesPanel.tsx
    listado: [
      'id_revision_elemento',
      'paciente_id',
      'caso_id',
      'revision_id',
      'elemento_caso_id',
      'prioridad_revision',
      'estado_revision_elemento',
    ].join(', '),
  },

  revisionHallazgos: {
    // src/hooks/useRevisionHallazgos.ts
    listado: [
      'id_revision_hallazgo',
      'paciente_id',
      'caso_id',
      'revision_id',
      'revision_elemento_id',
      'revision_aspecto_id',
      'elemento_caso_id',
      'categoria_hallazgo',
      'tipo_hallazgo',
      'subtipo_hallazgo',
      'descripcion_hallazgo',
      'intensidad_hallazgo_porcentaje',
      'nivel_bloqueo_porcentaje',
      'origen_sugerido',
      'fuente_deteccion',
      'nivel_confirmacion',
      'requiere_seguimiento',
      'prioridad_hallazgo',
      'estado_hallazgo',
      'informacion_canalizada',
      'observaciones',
      'notas_internas',
      'created_at',
      'updated_at',
    ].join(', '),
  },

  agendaOperativa: {
    // AgendaPage.tsx - vista_agenda_operativa
    listado: [
      'id_agenda_evento',
      'solicitud_agenda_id',
      'paciente_id',
      'consulta_id',
      'evaluacion_id',
      'caso_id',
      'revision_id',
      'trabajo_id',
      'trabajo_sesion_id',
      'tipo_evento',
      'estado_evento',
      'origen_evento',
      'titulo_evento',
      'titulo_publico',
      'fecha_inicio',
      'fecha_fin',
      'modalidad',
      'requiere_confirmacion',
      'confirmado_por_paciente',
      'google_calendar_sync_estado',
      'estado_solicitud',
      'origen_solicitud',
      'fecha_solicitud',
      'nombre_contacto',
      'email_contacto',
      'telefono_contacto',
      'nombre_operativo',
      'tipo_contexto',
      'created_at',
      'updated_at',
    ].join(', '),
    // AgendaPage.tsx - agenda_eventos (detalle para edicion)
    detalle: [
      'id_agenda_evento',
      'titulo_evento',
      'tipo_evento',
      'estado_evento',
      'fecha_inicio',
      'fecha_fin',
      'modalidad',
      'ubicacion',
      'enlace_online',
      'notas_internas',
    ].join(', '),
  },
} as const
